{% set name = "createrepo_c" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rpm-software-management/createrepo_c/archive/{{ version }}/createrepo_c-{{ version }}.tar.gz
  sha256: c2236d5032158c47d8e4d5cc377a91953f27834f3420088264bd62b27b668b9a

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - cmake
    - pkg-config
  host:
    - python
    - zchunk
    - libcurl
    - openssl
    - xz
    - libmagic
    - sqlite
    - libxml2
    - glib
    - bzip2
    - rpm-tools
    - drpm
    - zlib
    - libmodulemd
    # Used for running tests
    - nose
  run:
    - python
    # https://abi-laboratory.pro/index.php?view=timeline&l=rpm
    - {{ pin_compatible('rpm-tools', max_pin="x.x") }}
    - {{ pin_compatible('libmodulemd', max_pin="x") }}

test:
  commands:
    - createrepo_c --help

about:
  home: http://rpm-software-management.github.io/createrepo_c/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: C implementation of createrepo
  description: |
    Createrepo_c is a C implementation of the classical [Createrepo](http://createrepo.baseurl.org/)
    tool and simultaneously a C library for manipulation with a repodata.
    Createrepo_c provides Python bindings too, so could be easily used instead
    of [yum library](http://yum.baseurl.org/) for certain kinds of
    manipulations with repodata.
  doc_url: https://github.com/rpm-software-management/createrepo_c/wiki
  dev_url: https://github.com/rpm-software-management/createrepo_c

extra:
  recipe-maintainers:
    - chrisburr
