{% set name = "createrepo_c" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rpm-software-management/createrepo_c/archive/{{ version }}/createrepo_c-{{ version }}.tar.gz
  sha256: b77277d0fde055fc942221a432017db333f3c0aa696ded36232f67b519f164a3

build:
  number: 2
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - cmake
    - pkg-config
  host:
    - python
    - zchunk
    - libcurl
    - openssl
    - xz
    - libmagic
    - sqlite
    - libxml2
    - glib
    - bzip2
    - rpm-tools
    - drpm
    - zlib
    - libmodulemd
    # Used for running tests
    - nose
  run:
    - python
    # https://abi-laboratory.pro/index.php?view=timeline&l=rpm
    - {{ pin_compatible('rpm-tools', max_pin="x.x") }}
    - {{ pin_compatible('libmodulemd', max_pin="x") }}

test:
  commands:
    - createrepo_c --help

about:
  home: http://rpm-software-management.github.io/createrepo_c/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: C implementation of createrepo
  description: |
    Createrepo_c is a C implementation of the classical [Createrepo](http://createrepo.baseurl.org/)
    tool and simultaneously a C library for manipulation with a repodata.
    Createrepo_c provides Python bindings too, so could be easily used instead
    of [yum library](http://yum.baseurl.org/) for certain kinds of
    manipulations with repodata.
  doc_url: https://github.com/rpm-software-management/createrepo_c/wiki
  dev_url: https://github.com/rpm-software-management/createrepo_c

extra:
  recipe-maintainers:
    - chrisburr
